app:
  name: "telecom rag api"
  version: "1.0.0"
  description: "telecom rag api"

data:
  vector_index_path: "faiss_telecom_index"
  chunk_size: 500
  chunk_overlap: 100
  batch_size: 50

models:
  embedding_provider: "huggingface"
  embedding_model_name: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  llm_provider: "gemini"
  llm_model_name: "gemini-2.5-flash"
  temperature: 0
  k_retrieval: 20